"""new tables 3

Revision ID: 0c2e53e0b041
Revises: 5c6bc4b88591
Create Date: 2026-09-01 18:20:01.353348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2e53e0b041'
down_revision: Union[str, Sequence[str], None] = '5c6bc4b88591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('phone', sa.String(length=10), nullable=True))
    op.add_column('userdata', sa.Column('additional_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'additional_details')
    op.drop_column('userdata', 'phone')
    # ### end Alembic commands ###
